---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/time/docker/sonarr:/config
      - /home/time/docker/sonarr:/tv #optional
      - /home/time/docker/sonarr:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped